# pull official base image
FROM python:3.10.6-slim-buster

# set working directory
WORKDIR /BASHer/snp_haplotyper

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_DEBUG 1
ENV FLASK_APP=/BASHer/snp_haplotyper/snp_haplotyper/app.py
ENV PYTHONPATH=/BASHer/snp_haplotyper/snp_haplotyper
ENV SESSION_FILE_DIR /var/local/basher/flask_sessions
ENV FLASK_DEBUG=1 
# only for development

# add and install requirements
COPY ./requirements.txt .
RUN pip3 install -r requirements.txt
USER 0 
RUN mkdir -p /var/local/basher/logs/
RUN mkdir -p /var/local/basher/uploads/
RUN mkdir -p /var/local/basher/flask_sessions/
RUN chmod 777 /var/local/basher/logs/
RUN chmod 777 /var/local/basher/uploads/
RUN chmod 777 /var/local/basher/flask_sessions/

USER $CONTAINER_USER_ID

RUN pip install debugpy
RUN apt-get update && apt-get install -y wkhtmltopdf

# add app
COPY . .

# run server
CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --host=0.0.0.0

